### ISSUE TITLE
Decrease Complexity

### ISSUE THREAD

**Issue by jrishabh720** [Devolena/Prime-Factors#2]
Decrease the Complexity of code.

**Comment by Devolopia** [comment]
Yes We can Decrease the complexity from O(n) to O(log<sub>2</sub>n);

**Comment by Devolena** [comment]
Can We further decrease the complexity

**Comment by avadiesel** [comment]
> Can We further decrease the complexity

Yes If we can use i += 2 instead off i++ then time complexity became half of previous.

**Comment by shalini09101998** [comment]
> > Can We further decrease the complexity
> 
> Yes If we can use i += 2 instead off i++ then time complexity became half of previous.

If we check on the multiple of ( 6 n - 1 ) and ( 6 n + 1 ) then we cover all prime numbers.
